### ISSUE TITLE
Sometimes unsorted In and Out bytes per pid

### ISSUE THREAD

**Issue by petr-stety-stetka** [ChangSpivey/netinfo#3]
Hi,
I am using netinfo-ffi (C wrapper), but i think this is related here.

Sometimes when I call netinfo_stat_get_bytes_per_pid it return all bytes given for pid, but when I call netinfo_stat_get_bytes_per_attr for In and Out it returns 0 bytes.

Sometimes it works well sometimes not. (Return both all bytes and in and out too).

For easier explanation, here is my output from my example:
```
Pid 9873, Out: 330 B, In: 330 B, All: 660 B            //330 + 330 = 660 good
Pid 14047, Out: 140 B, In: 997 B, All: 1137 B        //140 + 997 = 660 good
Pid 20468, Out: 0 B, In: 0 B, All: 5156662 B          //0 + 0 != 5156662 problem
```

And here is my example source code:

```
void get_net_stat(ni_netinfo netinfo) 
{
    ni_net_statistics stat; 
    memset(&stat, 0, sizeof(ni_net_statistics));

    handle_error(netinfo_get_net_statistics(netinfo, &stat));

    ni_pid* pids = 0;
    uint32_t num_pids = 0;
    handle_error(netinfo_stat_get_all_pids(stat, &pids, &num_pids));
    for(uint32_t i = 0; i < num_pids; i++) {

      uint64_t bytes_out = 1;
      uint64_t bytes_in = 1;
      uint64_t bytes_all = 1;

      ni_inout inout = NETINFO_IOT_OUTGOING;
      ni_transport_type transport_type = NULL;
      handle_error(netinfo_stat_get_bytes_per_attr(stat, &pids[i], &inout, &transport_type, &bytes_out));

      inout = NETINFO_IOT_INCOMING;
      transport_type = NULL;
      handle_error(netinfo_stat_get_bytes_per_attr(stat, &pids[i], &inout, &transport_type, &bytes_in));

      handle_error(netinfo_stat_get_bytes_per_pid(stat, pids[i], &bytes_all));
      
      printf("Pid %d, Out: %d B, In: %d B, All: %d B\n", pids[i], bytes_out, bytes_in, bytes_all);

    }

    handle_error(netinfo_free_pid_array(pids, num_pids));

    handle_error(netinfo_free_stat(stat));
}
```

It's given the limitations of the library or cpu, so it misses filter, or where is the problem? Is there any way to solve it?

**Comment by kaegi** [comment]
The problem is here:

```c
ni_transport_type transport_type = NULL;
netinfo_stat_get_bytes_per_attr(stat, &pids[i], &inout, &transport_type, &bytes_out);
```

The thing you probably want is:

```c
netinfo_stat_get_bytes_per_attr(stat, &pids[i], &inout, NULL, &bytes_out);
```

Because there is no option type in C, I modeled the `None` value as `NULL` pointer and the `Some(value)` as `&value`. Because `NULL == 0 == NETINFO_TT_TCP`, you only count the TCP network packets with your original version.

I've not tested this code, so please let me know whether that solved the problem!

**Comment by petr-stety-stetka** [comment]
Unfortunately, when I pass NULL I get Segmentation fault. That is why I pass the pointer.

**Comment by kaegi** [comment]
This is a bug in the wrapper library (null testing on wrong pointer), and now fixed with the latest version. Thank you for reporting the bug!

[there is some compilation bug in the dependency [pnet](https://github.com/libpnet/libpnet), which is being worked on this very second; so compiling the project might not work right now]

**Comment by petr-stety-stetka** [comment]
Thx for fix :)
Now it is working.
